In [1]:
import pandas as pd

In [5]:
df=pd.DataFrame({
    'col1' : [1,2,3,4,5],
    'col2' : [45,56,67,34,34],
    'col3': 'ritesh kumar nahak ineur one'.split()
})

In [6]:
df

col1  col2    col3
0     1    45  ritesh
1     2    56   kumar
2     3    67   nahak
3     4    34   ineur
4     5    34     one

In [12]:
# Creat a col4 and put value as square of col1

In [40]:
df['col4']=df['col1']**2

In [13]:
df

col1  col2    col3  col4
0     1    45  ritesh     1
1     2    56   kumar     4
2     3    67   nahak     9
3     4    34   ineur    16
4     5    34     one    25

In [15]:
# Craet col 5 and put value as first letter of col3 string

In [41]:
df['col5']=df['col3'].str[0]

In [16]:
df

col1  col2    col3  col4 col5
0     1    45  ritesh     1    r
1     2    56   kumar     4    k
2     3    67   nahak     9    n
3     4    34   ineur    16    i
4     5    34     one    25    o

In [42]:
# Creat a col4 and put value as square of col1 using outside fucnction

In [43]:
def test(a):
    return a**2

In [44]:
df['col4_4']=df['col1'].apply(test)

In [45]:
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7  col7_7      col8
0     1    45  ritesh     1    r       1    r      r     5       6  3.806662
1     2    56   kumar     4    k       4    z      z     5       5  4.025352
2     3    67   nahak     9    n       9    z      z     5       5  4.204693
3     4    34   ineur    16    i      16    z      z     5       5  3.526361
4     5    34     one    25    o      25    z      z     5       3  3.526361

In [46]:
# Creat a col6 and put value as r if value in col 5 is r else put z

In [20]:
def test1(a):
    if a == 'r':
        return 'r'
    else:
        return 'z'

In [21]:
df['col6']=df['col5'].apply(test1)

In [22]:
df

col1  col2    col3  col4 col5  col4_4 col6
0     1    45  ritesh     1    r       1    r
1     2    56   kumar     4    k       4    z
2     3    67   nahak     9    n       9    z
3     4    34   ineur    16    i      16    z
4     5    34     one    25    o      25    z

In [47]:
# Creat a col6 and put value as r if value in col 5 is r else put z(instead of ourside function use lamda)

In [25]:
df["col6_6"]=df["col5"].apply(lambda a:'r' if a == 'r' else 'z')

In [26]:
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6
0     1    45  ritesh     1    r       1    r      r
1     2    56   kumar     4    k       4    z      z
2     3    67   nahak     9    n       9    z      z
3     4    34   ineur    16    i      16    z      z
4     5    34     one    25    o      25    z      z

In [ ]:
# Craet col7 which will store length of string of col3

In [48]:
df['col7']=len(df['col3'])   # This is wrong approach..

In [30]:
df['col7_7']=df['col3'].apply(len)

In [31]:
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7  col7_7
0     1    45  ritesh     1    r       1    r      r     5       6
1     2    56   kumar     4    k       4    z      z     5       5
2     3    67   nahak     9    n       9    z      z     5       5
3     4    34   ineur    16    i      16    z      z     5       5
4     5    34     one    25    o      25    z      z     5       3

In [36]:
# Craete col 8 which will hold log value of col2

In [37]:
import math   # as math package in not available in python core

In [38]:
df['col8']=df['col2'].apply(math.log)

In [39]:
df

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7  col7_7      col8
0     1    45  ritesh     1    r       1    r      r     5       6  3.806662
1     2    56   kumar     4    k       4    z      z     5       5  4.025352
2     3    67   nahak     9    n       9    z      z     5       5  4.204693
3     4    34   ineur    16    i      16    z      z     5       5  3.526361
4     5    34     one    25    o      25    z      z     5       3  3.526361

In [50]:
# Lets learn NUMPY(numerical python)

In [51]:
import numpy as np

In [52]:
l=['ritu',2,4,5,6]

In [54]:
np.array(l)   # pass list in aray

array(['ritu', '2', '4', '5', '6'], dtype='<U11')

In [55]:
type(np.array(l))    #nd array = n dimension aray

numpy.ndarray

In [56]:
np.array([3,4,5,6,3.0])  # upcast all int to floating if one in floaing

array([3., 4., 5., 6., 3.])

In [59]:
a=np.array([[1,2],[3,4]])

In [60]:
a

array([[1, 2],
       [3, 4]])

In [61]:
# pull 4 out of a

In [62]:
# 1 is available in 0th row and 0th column similarly 4 is available at 1st row and 1st column 

In [63]:
a[1][1]

4

In [64]:
a1=np.array([3,4,5,6,3.0])

In [65]:
a1[1]

4.0

In [68]:
np.array([1,2,3,4],ndmin=1)

array([1, 2, 3, 4])

In [69]:
np.array([1,2,3,4],ndmin=2)     # Two dimension array

array([[1, 2, 3, 4]])

In [70]:
np.array([1,2,3,4],ndmin=3)   # Three dimension array

array([[[1, 2, 3, 4]]])

In [71]:
a2=np.array([1,2,3,4],ndmin=3)

In [75]:
a2[0][0][0]     # as array is 3d array so give index 3 times

1

In [76]:
a      # this is 2 dimension array

array([[1, 2],
       [3, 4]])

In [78]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [79]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [80]:
np.mat([1,2,3,4,5])     # at min matrix will give 2 dimension only not less than that but array can have zero,1,2,3.....

matrix([[1, 2, 3, 4, 5]])

In [81]:
a=[1,2,3,4,5]

In [82]:
np.asanyarray(a)   # Here asanyarray convert list to array

array([1, 2, 3, 4, 5])

In [83]:
np.mat(a)   # matrix is subclass of array

matrix([[1, 2, 3, 4, 5]])

In [85]:
np.asanyarray(np.mat(a))    # Here asannyarray didnt covert matrix to array as asanyarray  first check whether somenthing is available in form of array 
# if not available in form of array then it wll convert .if available it wont convert to array.

matrix([[1, 2, 3, 4, 5]])

In [86]:
np.fromfunction(lambda i,j : i==j ,(3,3)) 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [87]:
np.fromfunction(lambda i,j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [88]:
np.fromfunction(lambda i,j : i*j,(4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [91]:
np.fromfunction(lambda i,j,k : i*j*k,(5,4,3),dtype = int)    # 3d matrix (3 array arranged in layer form)
# (5,4,3) means we want 5 such matrixes of 4*3

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  1,  2],
        [ 0,  2,  4],
        [ 0,  3,  6]],

       [[ 0,  0,  0],
        [ 0,  2,  4],
        [ 0,  4,  8],
        [ 0,  6, 12]],

       [[ 0,  0,  0],
        [ 0,  3,  6],
        [ 0,  6, 12],
        [ 0,  9, 18]],

       [[ 0,  0,  0],
        [ 0,  4,  8],
        [ 0,  8, 16],
        [ 0, 12, 24]]])

In [93]:
np.fromfunction(lambda i,j,k,l : i*j*k*l,(4,3,2,2),dtype = int)
#(4,3,2,2) means 2*2 array , 3 such array in one bundle ,4 such bundle 

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [94]:
a=np.fromfunction(lambda i,j,k : i*j*k,(5,4,3),dtype = int)

In [95]:
a.ndim  # tell it is 3d array

3

In [96]:
a.size # total 60 element inside the array

60

In [97]:
a.shape

(5, 4, 3)

In [99]:
a.dtype

dtype('int32')

In [100]:
# Covert array to dataframe

In [101]:
pd.DataFrame(a)   # As dataframe is 2d array so u cant pass 3d,,,for 2d u can creat

ValueError: Must pass 2-d input. shape=(5, 4, 3)

In [102]:
# Creat a dataframe of 200 row and 100 column logic of values  is i*j

In [107]:
a=np.fromfunction(lambda i,j : i*j ,(200,100),dtype = int)

In [108]:
pd.DataFrame(a)

0    1    2    3    4    5     6     7     8     9   ...     90     91  \
0     0    0    0    0    0    0     0     0     0     0  ...      0      0   
1     0    1    2    3    4    5     6     7     8     9  ...     90     91   
2     0    2    4    6    8   10    12    14    16    18  ...    180    182   
3     0    3    6    9   12   15    18    21    24    27  ...    270    273   
4     0    4    8   12   16   20    24    28    32    36  ...    360    364   
..   ..  ...  ...  ...  ...  ...   ...   ...   ...   ...  ...    ...    ...   
195   0  195  390  585  780  975  1170  1365  1560  1755  ...  17550  17745   
196   0  196  392  588  784  980  1176  1372  1568  1764  ...  17640  17836   
197   0  197  394  591  788  985  1182  1379  1576  1773  ...  17730  17927   
198   0  198  396  594  792  990  1188  1386  1584  1782  ...  17820  18018   
199   0  199  398  597  796  995  1194  1393  1592  1791  ...  17910  18109   

        92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0  
1       92     93     94     95     96     97     98     99  
2      184    186    188    190    192    194    196    198  
3      276    279    282    285    288    291    294    297  
4      368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...  
195  17940  18135  18330  18525  18720  18915  19110  19305  
196  18032  18228  18424  18620  18816  19012  19208  19404  
197  18124  18321  18518  18715  18912  19109  19306  19503  
198  18216  18414  18612  18810  19008  19206  19404  19602  
199  18308  18507  18706  18905  19104  19303  19502  19701  

[200 rows x 100 columns]

In [ ]:
## Random 

In [109]:
np.random.rand(100,4)

array([[8.34221914e-01, 2.98534250e-02, 7.82167860e-01, 7.89617585e-01],
       [9.01250658e-01, 7.87954857e-02, 5.84720176e-01, 1.55363654e-01],
       [9.81560048e-01, 2.35348298e-01, 8.24760491e-01, 9.55550549e-01],
       [6.87968168e-01, 8.72269016e-01, 4.21881572e-01, 8.80949315e-01],
       [3.46716368e-01, 1.90425565e-01, 1.19067819e-01, 6.67665454e-01],
       [9.90263665e-01, 2.85301281e-02, 7.50397671e-01, 8.18583700e-01],
       [3.11518354e-01, 5.23091961e-01, 4.70406677e-01, 5.53414239e-01],
       [5.03260135e-01, 8.83394679e-01, 6.59995698e-02, 1.75250234e-01],
       [1.08738770e-03, 8.47039114e-01, 6.84345231e-01, 7.26036290e-01],
       [3.76827501e-01, 9.25040444e-01, 9.61819237e-01, 3.68682018e-01],
       [5.51406475e-01, 3.82141851e-01, 4.49364976e-01, 8.80814618e-01],
       [6.01214913e-01, 8.50728065e-01, 3.74260880e-01, 4.70768827e-01],
       [8.11804191e-01, 2.86042768e-01, 8.60026060e-01, 3.20274321e-01],
       [8.27485079e-01, 7.62085175e-01, 5.35127091e

In [111]:
np.random.randint(4,100)   # it will generate random ineger for you

61

In [115]:
np.random.randn(4,5)

array([[-0.63317101, -1.69442384,  0.18720066,  3.16483762, -0.49729474],
       [-0.12382513, -0.53891774, -0.37410302,  1.77991671,  0.19542961],
       [ 0.87305562, -0.46997944,  0.68109043, -0.63781641, -0.72125728],
       [-1.07098768,  1.46396224,  0.76546597,  0.37124763, -2.25643689]])

In [114]:
# Difference between rand and randn
#rand= will give random number 
#randn=will give random number but will have normal distribution(avg =0 and standard deviation =1)

In [116]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.205607  0.507262 -0.331664 -0.640434 -1.062765
1 -0.355627 -0.575158  1.262409 -0.742441  0.256821
2 -0.883565  0.955084  1.077151 -0.426439  1.619205
3 -0.608516 -0.256053 -0.483957 -0.174999  0.835045

In [ ]:
# Covert dimension from 3dto 2d to covet it to data frame

In [118]:
a=np.fromfunction(lambda i,j,k : i*j*k,(5,4,3),dtype = int)

In [119]:
a

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  1,  2],
        [ 0,  2,  4],
        [ 0,  3,  6]],

       [[ 0,  0,  0],
        [ 0,  2,  4],
        [ 0,  4,  8],
        [ 0,  6, 12]],

       [[ 0,  0,  0],
        [ 0,  3,  6],
        [ 0,  6, 12],
        [ 0,  9, 18]],

       [[ 0,  0,  0],
        [ 0,  4,  8],
        [ 0,  8, 16],
        [ 0, 12, 24]]])

In [120]:
a.reshape(10,6)
# (5,4,3)=60 for make i*j =60 for 2d

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  2],
       [ 0,  2,  4,  0,  3,  6],
       [ 0,  0,  0,  0,  2,  4],
       [ 0,  4,  8,  0,  6, 12],
       [ 0,  0,  0,  0,  3,  6],
       [ 0,  6, 12,  0,  9, 18],
       [ 0,  0,  0,  0,  4,  8],
       [ 0,  8, 16,  0, 12, 24]])

In [122]:
pd.DataFrame(a.reshape(10,6))

0  1   2  3   4   5
0  0  0   0  0   0   0
1  0  0   0  0   0   0
2  0  0   0  0   1   2
3  0  2   4  0   3   6
4  0  0   0  0   2   4
5  0  4   8  0   6  12
6  0  0   0  0   3   6
7  0  6  12  0   9  18
8  0  0   0  0   4   8
9  0  8  16  0  12  24

In [123]:
# 3d to 4d

In [124]:
a=np.fromfunction(lambda i,j,k : i*j*k,(5,4,3),dtype = int)

In [125]:
a.reshape(2,2,3,5)

array([[[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  1,  2,  0,  2],
         [ 4,  0,  3,  6,  0],
         [ 0,  0,  0,  2,  4]]],


       [[[ 0,  4,  8,  0,  6],
         [12,  0,  0,  0,  0],
         [ 3,  6,  0,  6, 12]],

        [[ 0,  9, 18,  0,  0],
         [ 0,  0,  4,  8,  0],
         [ 8, 16,  0, 12, 24]]]])

In [126]:
a.reshape(2,-1)  # System will automatcally check 60= 2*(possible multiples)
# you can take any negative number (-1 is not compulsion)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         1,  2,  0,  2,  4,  0,  3,  6,  0,  0,  0,  0,  2,  4],
       [ 0,  4,  8,  0,  6, 12,  0,  0,  0,  0,  3,  6,  0,  6, 12,  0,
         9, 18,  0,  0,  0,  0,  4,  8,  0,  8, 16,  0, 12, 24]])

In [127]:
list(range(4,10,2))

[4, 6, 8]

In [128]:
list(range(4,10,0.2))   # in range u cant use float value so use arange in numpy

TypeError: 'float' object cannot be interpreted as an integer

In [131]:
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [132]:
arr=np.random.rand(4,5)

In [133]:
arr

array([[0.10284651, 0.35595883, 0.30208721, 0.94537594, 0.78616973],
       [0.10447213, 0.52636108, 0.32227428, 0.87038677, 0.28786035],
       [0.06579315, 0.96013943, 0.39448334, 0.3364112 , 0.67500948],
       [0.85447018, 0.14019934, 0.53537148, 0.21002709, 0.50155894]])

In [134]:
# extract all data whicle has value greater than 0.5

In [137]:
arr[arr>0.5]  # similar to pandas

array([0.94537594, 0.78616973, 0.52636108, 0.87038677, 0.96013943,
       0.67500948, 0.85447018, 0.53537148, 0.50155894])

In [143]:
arr

array([[0.10284651, 0.35595883, 0.30208721, 0.94537594, 0.78616973],
       [0.10447213, 0.52636108, 0.32227428, 0.87038677, 0.28786035],
       [0.06579315, 0.96013943, 0.39448334, 0.3364112 , 0.67500948],
       [0.85447018, 0.14019934, 0.53537148, 0.21002709, 0.50155894]])

In [144]:
arr[[1,2],[2]]  # similar to pandas 

array([0.32227428, 0.39448334])

In [145]:
arr=np.random.rand(8,5)

In [146]:
arr

array([[0.23004552, 0.91623938, 0.21605439, 0.15816665, 0.96548792],
       [0.99932324, 0.11083505, 0.14461143, 0.01435344, 0.98355499],
       [0.39433329, 0.78051032, 0.28213476, 0.86418334, 0.68266963],
       [0.00378116, 0.92008622, 0.85208946, 0.77844377, 0.06273544],
       [0.13246443, 0.15954389, 0.48610808, 0.93628679, 0.64859827],
       [0.74660062, 0.38486897, 0.00212645, 0.25122539, 0.7782427 ],
       [0.69840749, 0.01850266, 0.87520604, 0.54451978, 0.53630694],
       [0.25043334, 0.23967285, 0.38870113, 0.19695782, 0.52241339]])

In [147]:
arr[1:8,0:3]   # 1 to 7 row and 0 to 2 column data

array([[0.99932324, 0.11083505, 0.14461143],
       [0.39433329, 0.78051032, 0.28213476],
       [0.00378116, 0.92008622, 0.85208946],
       [0.13246443, 0.15954389, 0.48610808],
       [0.74660062, 0.38486897, 0.00212645],
       [0.69840749, 0.01850266, 0.87520604],
       [0.25043334, 0.23967285, 0.38870113]])

In [153]:
a2=arr[1:8,[0,1,2]] 

In [154]:
a2

array([[0.99932324, 0.11083505, 0.14461143],
       [0.39433329, 0.78051032, 0.28213476],
       [0.00378116, 0.92008622, 0.85208946],
       [0.13246443, 0.15954389, 0.48610808],
       [0.74660062, 0.38486897, 0.00212645],
       [0.69840749, 0.01850266, 0.87520604],
       [0.25043334, 0.23967285, 0.38870113]])

In [155]:
# replace first data with 1111

In [157]:
a2[0][0] =1111

In [158]:
a2

array([[1.11100000e+03, 1.10835047e-01, 1.44611426e-01],
       [3.94333291e-01, 7.80510317e-01, 2.82134760e-01],
       [3.78115676e-03, 9.20086216e-01, 8.52089457e-01],
       [1.32464429e-01, 1.59543888e-01, 4.86108078e-01],
       [7.46600617e-01, 3.84868967e-01, 2.12644511e-03],
       [6.98407493e-01, 1.85026558e-02, 8.75206039e-01],
       [2.50433337e-01, 2.39672850e-01, 3.88701127e-01]])

In [159]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[4,5]])

In [161]:
a

array([[1, 2],
       [3, 4]])

In [162]:
b

array([[2, 3],
       [4, 5]])

In [160]:
a*b # its not matrix multiplication its just a element multipliction

array([[ 2,  6],
       [12, 20]])

In [163]:
m=a*b

In [164]:
m/0   # in numpy u wont get zero division error lke core python, it will show inf

C:\Users\dell\AppData\Local\Temp/ipykernel_9608/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])