In [1]:
import numpy as np

In [2]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.zeros(5)   # Creat 1d array(1row) value containing 0

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [11]:
np.zeros((3,4),dtype=int)   # Creat 2d array haviing 3row and 4 column value containing 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
# np.zeros & np.ones available not more than that

In [15]:
5+np.ones((3,4),dtype=int)    # 5 is scalar and np.ones((3,4),dtype=int) is vector
# broadcasting(if we are trying to perform a=same kind of operation with all the element available in my space)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [17]:
np.empty((4,5))  # empty=Very very small no(close to zero)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306, 1.33511018e-306],
       [1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
        2.22522053e-306, 1.11261095e-306],
       [1.42417221e-306, 1.33512648e-306, 7.56596412e-307,
        2.22522596e-306, 2.22522596e-306]])

In [18]:
np.linspace(2,6)  # By default 50 value is generated ,it will generate 1d array only

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [20]:
np.linspace(1,1.5,20) # 20 number generated

array([1.        , 1.02631579, 1.05263158, 1.07894737, 1.10526316,
       1.13157895, 1.15789474, 1.18421053, 1.21052632, 1.23684211,
       1.26315789, 1.28947368, 1.31578947, 1.34210526, 1.36842105,
       1.39473684, 1.42105263, 1.44736842, 1.47368421, 1.5       ])

In [21]:
#np.linspace(1,1.5,20) as it always give 1d array covert it to 2d array

In [27]:
np.linspace(1,1.5,20).reshape(2,5) # as 20 != 2*5

ValueError: cannot reshape array of size 20 into shape (2,5)

In [28]:
np.linspace(1,1.5,20).reshape(4,5)

array([[1.        , 1.02631579, 1.05263158, 1.07894737, 1.10526316],
       [1.13157895, 1.15789474, 1.18421053, 1.21052632, 1.23684211],
       [1.26315789, 1.28947368, 1.31578947, 1.34210526, 1.36842105],
       [1.39473684, 1.42105263, 1.44736842, 1.47368421, 1.5       ]])

In [29]:
np.linspace(1,1.5,20,endpoint=False).reshape(2,-1)

array([[1.   , 1.025, 1.05 , 1.075, 1.1  , 1.125, 1.15 , 1.175, 1.2  ,
        1.225],
       [1.25 , 1.275, 1.3  , 1.325, 1.35 , 1.375, 1.4  , 1.425, 1.45 ,
        1.475]])

In [30]:
# endpoint= False mean it wont consider upper limit i.e is 1.5 for this case

In [31]:
# linespace doesnot consider stepsize like range function so use can use retstep

In [32]:
np.linspace(2,50,20,endpoint=False,retstep=True)

(array([ 2. ,  4.4,  6.8,  9.2, 11.6, 14. , 16.4, 18.8, 21.2, 23.6, 26. ,
        28.4, 30.8, 33.2, 35.6, 38. , 40.4, 42.8, 45.2, 47.6]),
 2.4)

In [33]:
# it automatically took 2.4 as stepsze for 20 samples

In [36]:
np.logspace(2,4,10) # similar to linespace but values is in log

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [37]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [45]:
np.arange(32).reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [46]:
a=np.arange(32).reshape(8,4)

In [47]:
a.max() #Return the maximum number

31

In [48]:
a.max(axis=1) # Max of each row

array([ 3,  7, 11, 15, 19, 23, 27, 31])

In [49]:
a.max(axis=0) # Max of each column

array([28, 29, 30, 31])

In [50]:
10+a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [51]:
a**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529],
       [576, 625, 676, 729],
       [784, 841, 900, 961]], dtype=int32)

In [52]:
pow(a,2)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529],
       [576, 625, 676, 729],
       [784, 841, 900, 961]], dtype=int32)

In [53]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [56]:
b=np.array([1,2,3,4])

In [57]:
a+b

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19],
       [17, 19, 21, 23],
       [21, 23, 25, 27],
       [25, 27, 29, 31],
       [29, 31, 33, 35]])

In [60]:
b=b.T

In [61]:
a+b # Transpose is not happening for b bcoz it is not possible to rotate 1d array

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19],
       [17, 19, 21, 23],
       [21, 23, 25, 27],
       [25, 27, 29, 31],
       [29, 31, 33, 35]])

In [68]:
b=np.array([1,2,3,4]).reshape(1,-1)

In [69]:
b

array([[1, 2, 3, 4]])

In [70]:
a+b

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19],
       [17, 19, 21, 23],
       [21, 23, 25, 27],
       [25, 27, 29, 31],
       [29, 31, 33, 35]])

In [78]:
b.T

array([[1],
       [2],
       [3],
       [4]])

In [80]:
a+b.T

ValueError: operands could not be broadcast together with shapes (8,4) (4,1) 

In [82]:
c=np.arange(16).reshape(4,4)

In [85]:
d=np.array([1,2,3,4])

In [86]:
d

array([1, 2, 3, 4])

In [87]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
c+d

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19]])

In [89]:
d+c.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [90]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [91]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436]])

In [92]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13]])

In [93]:
np.log10(a)

C:\Users\dell\AppData\Local\Temp/ipykernel_7452/547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 ],
       [1.30103   , 1.32221929, 1.34242268, 1.36172784],
       [1.38021124, 1.39794001, 1.41497335, 1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169]])

In [94]:
x=np.array([1,2,3,4])

In [95]:
y=x

In [96]:
y

array([1, 2, 3, 4])

In [97]:
z=np.copy(x)

In [98]:
z

array([1, 2, 3, 4])

In [99]:
x[0]=100

In [100]:
y

array([100,   2,   3,   4])

In [101]:
z

array([1, 2, 3, 4])

In [103]:
# Y=X it is not going to reserve new memory memory both will be store as  same location  i.e if x change y change
# This operstion is called as shallow copy

In [104]:
#z=np.copy(x) z creat copy in new location so even if x change z wont change as it stored in different location.
# This operstion is called as deep copy

In [105]:
print(id(x),id(y),id(z))

2107044531440 2107044531440 2107044530288
